name: datav8
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.1.8
  equatable: ^1.1.1
  carousel_pro: ^1.0.0
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.3.0
  shimmer: ^1.1.1
  flutter_bloc: ^3.2.0
  provider: ^4.0.4
  shared_preferences: ^0.5.6+3
  flutter_spinkit: ^4.1.2+1
  rxdart: ^0.23.0
  graphql: ^3.0.0
  tuple: ^1.0.3
  charts_flutter: ^0.9.0
  intl: ^0.16.1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  fonts:
    - family : Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight : 600

  assets:
    - assets/image/logo_kl.png
    - assets/image/logo_dark_kl.png
    - assets/image/placeholder255x255.png
    - assets/image/no_message.png
    - assets/image/no_message1.png
    - assets/image/no_message2.png
    - assets/image/banner/banner1.png
    - assets/image/banner/banner2.png
    - assets/image/banner/banner3.png
    - assets/image/banner/banner4.png
    - assets/image/icon/notification.png
    - assets/image/icon/creditAcount.png
    - assets/image/icon/chat.png
    - assets/image/icon/setting.png
    - assets/image/icon/callcenter.png
    - assets/image/icon/aboutapp.png
    - assets/image/icon/015-alert.png
    - assets/image/splash_screen.png
    - assets/image/icon/icon_image.png
    - assets/image/loginHeader.png

    - assets/icon/icon-settings.png
    - assets/icon/icon-manager.png
    - assets/icon/icon-management.png
    - assets/icon/icon-blueprint.png
    - assets/icon/icon-smartphone-info.png
    - assets/icon/icon-power.png
    - assets/icon/icon-info.png

  